//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuryAppDebloater.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuryAppDebloater.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download App Info.
        /// </summary>
        internal static string appBtn {
            get {
                return ResourceManager.GetString("appBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced.
        /// </summary>
        internal static string btnAdv {
            get {
                return ResourceManager.GetString("btnAdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uninstaller.
        /// </summary>
        internal static string btnMain {
            get {
                return ResourceManager.GetString("btnMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        internal static string btnOptions {
            get {
                return ResourceManager.GetString("btnOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download Android SDK Platform-Tools.
        /// </summary>
        internal static string btnSDK {
            get {
                return ResourceManager.GetString("btnSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string lblAbout {
            get {
                return ResourceManager.GetString("lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help and Contact.
        /// </summary>
        internal static string lblHelp {
            get {
                return ResourceManager.GetString("lblHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This program contains a modified and simplified version of Android SDK Platform-Tools, you can
        ///do some functions but it is very limited.
        ///If you want to use the full version of Android SDK Platform-Tools, click the button to download it..
        /// </summary>
        internal static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change language.
        /// </summary>
        internal static string lblLang {
            get {
                return ResourceManager.GetString("lblLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        internal static string lblOpt {
            get {
                return ResourceManager.GetString("lblOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced Mode.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Special Thanks to: Ricaidito, AbrahamJLR
        ///and Ts-Pytham.
        /// </summary>
        internal static string thanksLbl {
            get {
                return ResourceManager.GetString("thanksLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to Fury App Debloater
        ///
        ///A program to uninstall Apps on Android devices
        ///
        ///Make sure you have USB debugging turned on, if it isn&apos;t, turn on the Options
        ///developer (this varies depending on your device).
        ///
        ///Connect your device to PC via USB
        ///If you have everything ready, proceed to press the &quot;Run CMD&quot; button.
        ///
        ///Once the console with your device appears, press Enter, copy and paste this line:
        ///
        ///
        ///pm uninstall -k --user 0 &apos;package name&apos;
        ///
        ///
        ///In &apos;package name&apos; replace it with the name of the App packa [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string txtInfo {
            get {
                return ResourceManager.GetString("txtInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check Updates.
        /// </summary>
        internal static string updateBtn {
            get {
                return ResourceManager.GetString("updateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updates.
        /// </summary>
        internal static string updateLbl {
            get {
                return ResourceManager.GetString("updateLbl", resourceCulture);
            }
        }
    }
}
